---
- hosts:
    - 127.0.0.1
  become: yes
  vars:
    badge:
      hostname: "{{ lookup('env', 'BADGE_HOSTNAME') | default('badge', true) }}"
      version: "{{ lookup('env', 'BADGE_VERSION') | default('master', true) }}"
    system:
      boot_options:
        - "dtoverlay=dwc2"
        - "dtoverlay=spi1-3cs"
        - "dtparam=spi=on"
        - "dtparam=i2c_arm=on"
        - "dtparam=i2c1=on"
        - "gpu_mem=16"
        - "disable_overscan=1"
        - "dtparam=audio=off"
      modules:
        - "i2c-dev"
        - "dwc2,g_ether"
    services:
      enable:
        # - dphys-swapfile.service
        # - pwnagotchi.service
        # - bettercap.service
        # - pwngrid-peer.service
        # - epd-fuse.service
        - fstrim.timer
      disable:
        - apt-daily.timer
        - apt-daily.service
        - apt-daily-upgrade.timer
        - apt-daily-upgrade.service
        # - wpa_supplicant.service
        - bluetooth.service
        # - triggerhappy.service
        # - ifup@wlan0.service
    packages:
      # bettercap:
      #   url: "https://github.com/bettercap/bettercap/releases/download/v2.27.1/bettercap_linux_armhf_v2.27.1.zip"
      #   ui: "https://github.com/bettercap/ui/releases/download/v1.3.0/ui.zip"
      # pwngrid:
      #   url: "https://github.com/evilsocket/pwngrid/releases/download/v1.10.1/pwngrid_linux_armhf_v1.10.1.zip"
      apt:
        hold:
          - firmware-atheros
          - firmware-brcm80211
          - firmware-libertas
          - firmware-misc-nonfree
          - firmware-realtek
        remove:
          - kali-defaults-desktop # metapackage
          - kali-desktop-base     # metapackage
          - kali-desktop-core     # metapackage
          - kali-desktop-xfce     # metapackage
          - kali-hidpi-mode       # metapackage
          - kali-themes           # metapackage
          - kali-tools-top10      # metapackage
          - raspberrypi-net-mods
          - dhcpcd5
          - triggerhappy
          - wpa_supplicant
          - nfs-common
          - pulseaudio
          - pipewire
        install:
          - rsync
          - vim
          - screen
          - golang
          - git
          - build-essential
          - python3-pip
          - python3-mpi4py
          - python3-smbus
          - python3-grpcio
          - python3-numpy
          - python3-pil
          - python3-smbus          
          - unzip
          - gawk
          - figlet
          - lolcat
          - libopenmpi-dev
          - libatlas-base-dev
          - tcpdump
          - lsof
          - htop
          #- libilmbase23
          #- libopenexr23
          #- libgstreamer1.0-0
          #- libavcodec58
          #- libavformat58
          #- libswscale5
          #- libpcap-dev
          #- libusb-1.0-0-dev
          #- libnetfilter-queue-dev
          - libopenmpi3
          - dphys-swapfile
          - fonts-dejavu
          - fonts-dejavu-core
          - fonts-dejavu-extra
          - libfuse-dev
          - bc
          - fonts-freefont-ttf
          - fbi
          - fonts-ipaexfont-gothic
          - cryptsetup
          - dnsmasq
 
  tasks:
  # - name: change hostname
  #   become: yes
  #   hostname:
  #     name: "{{badge.hostname}}"
  #     use: debian
  #   register: hostname

  - name: add hostname {{ badge.hostname }} to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.1\.1[ \t]+kali'
      line: "127.0.1.1\t{{badge.hostname}}"
      state: present

  # - name: set hostname
  #   command: hostname "{{badge.hostname}}"

  - name: changing hostname to {{ badge.hostname }}
    copy:
      content: "{{ badge.hostname }}{{'\n'}}"
      dest: /etc/hostname
      backup: false

  - name: disable sap plugin for bluetooth.service
    lineinfile:
      dest: /lib/systemd/system/bluetooth.service
      regexp: '^ExecStart=/usr/lib/bluetooth/bluetoothd$'
      line: 'ExecStart=/usr/lib/bluetooth/bluetoothd --noplugin=sap'
      state: present

  - name: remove unnecessary apt packages
    apt:
      name: "{{ packages.apt.remove }}"
      state: absent
      purge: yes

  # - name: upgrade apt distro
  #   apt:
  #     upgrade: dist
  #     update_cache: yes
  #   async: 1200
  #   poll: 0
  #   register: upgrade_task      

  # - name: check upgrade
  #   async_status:
  #     jid: "{{ upgrade_task.ansible_job_id }}"
  #   register: upgrade_status
  #   until: upgrade_status.finished
  #   retries: 60
  #   delay: 60

  - name: install packages
    apt:
      name: "{{ packages.apt.install }}"
      state: present
      install_recommends: no
    async: 1200
    poll: 0
    register: package_installer      

  - name: wait for packages
    async_status:
      jid: "{{ package_installer.ansible_job_id }}"
    register: install_result
    until: install_result.finished
    retries: 20
    delay: 60

  # - name: configure dphys-swapfile
  #   copy:
  #     dest: /etc/dphys-swapfile
  #     content: "CONF_SWAPSIZE=1024"
  #     force: no

  - name: add HDMI powersave to rc.local
    blockinfile:
      path: /etc/rc.local
      insertbefore: "exit 0"
      create: yes
      block: |
        if ! /opt/vc/bin/tvservice -s | egrep 'HDMI|DVI'; then
          /opt/vc/bin/tvservice -o
        fi

  - name: configuring network interfaces
    copy:
      dest: "/etc/network/interfaces"
      content: |
        auto lo
        iface lo inet loopback
        auto wlan0
        allow-hotplug wlan0
        iface wlan0 inet dhcp
        wpa-ssid your-ssid
        wpa-psk your-password

  - name: enable ssh on boot
    file:
      path: /boot/ssh
      state: touch

  - name: adjust /boot/config.txt
    lineinfile:
      dest: /boot/config.txt
      insertafter: EOF
      create: yes
      line: '{{ item }}'
    with_items: "{{system.boot_options}}"

  - name: disable gui
    command: systemctl set-default multi-user.target

  - name: adjust /etc/modules
    lineinfile:
      dest: /etc/modules
      insertafter: EOF
      create: yes
      line: '{{ item }}'
    with_items: "{{system.modules}}"

  - name: clean apt cache
    apt:
      autoclean: yes

  - name: remove dependencies that are no longer required
    apt:
      autoremove: yes

  - name: disable unnecessary services
    systemd:
      name: "{{ item }}"
      state: stopped
      enabled: no
    with_items: "{{ services.disable }}"

  - name: install python package spidev
    command: pip3 install RPi.GPIO spidev

  - name: clone waveshare e-paper repository
    git:
      repo: https://github.com/waveshare/e-Paper
      dest: /usr/local/src/e-Papers

  - name: disable kali developer message when logging in
    command: touch ~/.hushlogin
